### Create
POST http://localhost:3000/user/create
content-type: application/json

{
  "username": "andy",
  "password": "test1234",
  "email": "andy3@podo.com"
}

### GetUser
GET http://localhost:3000/user/getUser/andy3@podo.com


### Update User
PUT http://localhost:3000/user/update/andy3@podo.com
content-type: application/json

{
  "email": "andy3@podo.com",
  "username": "andy2",
  "password": "test12345"
}

### Delete User
DELETE http://localhost:3000/user/delete/andy3@podo.com